"""A readable pandas-based framework for research workflows: dataset
handling with tracked model specifications, reusable column transforms,
and a Monte Carlo simulation module."""

from .experiment import (
    ExperimentSize,
    assign_groups,
    compare_groups,
    cuped_adjust,
    detectable_lift_for_mean,
    detectable_lift_for_proportion,
    pretest_balance,
    sample_size_for_mean,
    sample_size_for_proportion,
)
from .pond import ModelSpec, Pond, PondLoadFailedError
from .simulation import (
    ConvergenceDiagnostics,
    DistributionSpec,
    InputManager,
    ModelFunction,
    MonteCarloEngine,
    Scenario,
    SensitivityAnalyzer,
    Simulation,
    SimulationResult,
)
from .transforms import (
    demean_by_group,
    interaction,
    log1p_transform,
    log_transform,
    mean_center,
    min_max_scale,
    rank_transform,
    row_mean,
    row_sum,
    safe_ratio,
    square,
    winsorize,
    z_score,
)
from .plotter import SimulationPlotter

__all__ = [
    "ConvergenceDiagnostics",
    "DistributionSpec",
    "ExperimentSize",
    "InputManager",
    "ModelFunction",
    "ModelSpec",
    "MonteCarloEngine",
    "Pond",
    "PondLoadFailedError",
    "Scenario",
    "SensitivityAnalyzer",
    "Simulation",
    "SimulationPlotter",
    "SimulationResult",
    "assign_groups",
    "compare_groups",
    "cuped_adjust",
    "demean_by_group",
    "detectable_lift_for_mean",
    "detectable_lift_for_proportion",
    "interaction",
    "log1p_transform",
    "log_transform",
    "mean_center",
    "min_max_scale",
    "pretest_balance",
    "rank_transform",
    "row_mean",
    "row_sum",
    "safe_ratio",
    "sample_size_for_mean",
    "sample_size_for_proportion",
    "square",
    "winsorize",
    "z_score",
]
